defmodule Readiness.Repo.TenantMigrations.AddResponsibilityCentreAreaResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:checklist_items, prefix: prefix()) do
      add :area_id, :uuid
    end

    create table(:checklist_areas, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:checklist_items, prefix: prefix()) do
      modify :area_id,
             references(:checklist_areas,
               column: :id,
               name: "checklist_items_area_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:checklist_areas, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:checklist_areas, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:checklist_items, "checklist_items_area_id_fkey")

    alter table(:checklist_items, prefix: prefix()) do
      modify :area_id, :uuid
    end

    drop table(:checklist_areas, prefix: prefix())

    alter table(:checklist_items, prefix: prefix()) do
      remove :area_id
    end
  end
end
